Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
        master.vm.box = "bento/ubuntu-22.04-arm64"
        master.vm.hostname = "master"

        master.vm.network :private_network, ip: "192.168.1.1"
        # Specify a provisioning script (shell script) to set up the Master.
        master.vm.provision "shell", path: "provision.sh"
        master.vm.provider "vmware-desktop" do |v|
            v.memory = 256
            v.name = "master"
        end
    end

    config.vm.define "slave" do |slave|
        slave.vm.box = "bento/ubuntu-22.04-arm64"
        slave.vm.hostname = "master"

        slave.vm.network :private_network, ip: "192.168.1.1"
        slave.vm.provision "ansible" do |ansible|
            ansible.playbook = "provision.yml"  # Path to your Ansible playbook
          end
        slave.vm.provider "vmware-desktop" do |v|
            v.memory = 256
            v.name = "master"
        end
    end
end